### ISSUE TITLE
work with different AWS profiles

### ISSUE THREAD

**Issue by linbynd** [achiku/jungle#20]
I am trying this out for the first time, I was wondering if it does work with different profiles in the credentials file. I see its pulling with just the default profile..

Great tool btw...

**Comment by achiku** [comment]
@linbynd I think it works with different AWS profiles since boto3 is used in this tool. Have you read through the following doc? If you have any problem that can't be solved after reading it, I would appreciate if you can tell me your ```jungle``` version and configuration and describe what a problem is.

http://boto3.readthedocs.org/en/latest/guide/configuration.html#guide-configuration

**Comment by achiku** [comment]
I'll close this issue by this pr. If you find any other problem, please let me know!

https://github.com/achiku/jungle/pull/23
